version: '3.8'

################################################################################
# SERVICES
################################################################################
services:

  # ------------------------------------------------------------
  # postgres
  # ------------------------------------------------------------
  postgres:
    image: postgres:${POSTGRES_DOCKER_VERSION}
    hostname: postgres
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_ROOT_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_ROOT_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
      - POSTGRES_NON_ROOT_USER=${POSTGRES_NON_ROOT_USER}
      - POSTGRES_NON_ROOT_PASSWORD=${POSTGRES_NON_ROOT_PASSWORD}
    ports:
      # [local-machine:]local-port:docker-port
      - "${LOCAL_LISTEN_ADDR}${HOST_PORT_PGSQL}:5432"      
    volumes:
      - postgresdata

################################################################################
# NETWORK
################################################################################

################################################################################
# VOLUMES
################################################################################
volumes:
  postgresdata:
     name: postgres-volume
     driver_opts:
      type: local
      device: ${POSTGRES_VOLUME}:/var/lib/postgresql/data