version: '3.8'

################################################################################
# SERVICES
################################################################################
services:

  # ------------------------------------------------------------
  # traefik
  # ------------------------------------------------------------
  mongo:
    image: mongo:${MONGO_DOCKER_VERSION}
    restart: always
    expose:
      - "27017"
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_DATABASE}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
    volumes:
      - mongodata

################################################################################
# NETWORK
################################################################################

################################################################################
# VOLUMES
################################################################################
volumes:
  mongodata:
     name: mongo-volume
     driver_opts:
      type: local
      device: ${MONGO_VOLUME}:/data/db